<?php

namespace r3pt1s\httpserver\util;

enum ActionFailureReason {

    case PATH_REGISTER_FAILED_VERSIONING_DISABLED;
    case PATH_REGISTER_FAILED_UNSUPPORTED_REQUEST_METHOD;
    case PATH_REGISTER_FAILED_API_VERSION_NOT_EXISTENT;

    case VERSION_REGISTER_FAILED_VERSIONING_DISABLED;
    case VERSION_REGISTER_FAILED_VERSION_EXISTS;
}